### ISSUE TITLE
Make custom fields hidden by default

### ISSUE THREAD

**Issue by basbebe** [davidnemec/bitwarden-to-keepass#3]
I know very little about the keepass format but I think it makes sense to make all custom fields added in Bitwarden "hidden" (or is it "secret"?) by default in the exported database.

Potential content of these fields is TOTP seeds, answers to security questions, PINs, recovery codes.

**Comment by davidnemec** [comment]
Yes, I agree. But it's currently not supported by pykeepass but it has an open PR for this libkeepass/pykeepass/pull/186. So when/if this gets merged I will use it for sure.

But having them exported as "non-protected" does not make them less secure. They are "just" visible as plaintext when you unlock your database and view tab with custom properties.

**Comment by basbebe** [comment]
Great?

> But having them exported as "non-protected" does not make them less secure. They are "just" visible as plaintext when you unlock your database and view tab with custom properties.

Yes I know – It would just more comfortable to have them hidden by default. (as opposed to hiding them "by hand")

**Comment by ccfiel** [comment]
The pull request is already merged. Can we make the change?
